### ISSUE TITLE
MM can't find the MMM-Wetteronline.js while booting (no docker)

### ISSUE THREAD

**Issue by pst-mng** [bogenpirat/MMM-WetterOnline#10]
I have a fresh installation of Rasp OS and MagicMirror. Everything is as up to date as possible.
I use an old Model B+ but MagicMirror works fine.
I installed as told in the readme and all files are there in the right modules folder.
Unfortunately, I got this messages while starting MagicMirror:

[WARN] No /home/raspi/MagicMirror/js/../modules/MMM-WetterOnline/MMM-WetterOnline.js found for module: MMM-WetterOnline.

MagicMirrow doesn't crash and all other active modules work fine.

Thanks for any assistence.

**Comment by bogenpirat** [comment]
what does
`ls -hal /home/raspi/MagicMirror/js/../modules/MMM-WetterOnline/MMM-WetterOnline.js`
look like?

**Comment by pst-mng** [comment]
Ah, here we go! There's no MMM-WetterOnline.js file to find. Just the MMM-WetterOnline-folder in the modules folder:
.../MagicMirror/modules/MMM-Wetteronline
As I have alost no experience with coding, would you guide me to create the .js file? Thanks a lot!

Edit:
There's a MMM-WetterOnline.js file in the folder /MagicMirror/modules/MMM-Wetteronline.

**Comment by bogenpirat** [comment]
if you followed the instructions, i think that file should exist. the initial `cd modules/` command needs to be issued from the MagicMirror folder. did it fail? for your path, i think this should work for cloning the code:

```bash
cd /home/raspi/MagicMirror/modules/
git clone https://github.com/bogenpirat/MMM-WetterOnline.git
```

**Comment by pst-mng** [comment]
Thanks a lot!
I updated and upgraded the whole system and then used your advice.
Now it works. Case is closed, thanks a lot!
