### ISSUE TITLE
TypeError issue

### ISSUE THREAD

**Issue by I4T2B** [bogenpirat/MMM-WetterOnline#3]
Hello, i have a issue with this module.
Here is a part of the logs:
> [26.06.2023 20:16.32.442] [ERROR] Whoops! There was an uncaught exception...
mm     | [26.06.2023 20:16.32.443] [ERROR] TypeError: Cannot read properties of undefined (reading 'attribs')
mm     |     at Element.<anonymous> (/opt/magic_mirror/modules/MMM-WetterOnline/node_helper.js:72:18)
mm     |     at LoadedCheerio.each (/opt/magic_mirror/modules/MMM-WetterOnline/node_modules/cheerio/lib/api/traversing.js:519:26)
mm     |     at IncomingMessage.<anonymous> (/opt/magic_mirror/modules/MMM-WetterOnline/node_helper.js:61:14)
mm     |     at IncomingMessage.emit (node:events:525:35)
mm     |     at endReadableNT (node:internal/streams/readable:1359:12)
mm     |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
mm     | [26.06.2023 20:16.32.443] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
mm     | [26.06.2023 20:16.32.444] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Can you please take a look at the problem. Thanks.

**Comment by bogenpirat** [comment]
i'm fashionably late, but i've fixed this in 80423446ba44a35495098a96b8ff1fc16fcfec51. feel free to do a `git pull`.

NB: if you had a userAgent option set in the config, you need to set it to a desktop browser.
