### ISSUE TITLE
Modul ladet nicht

### ISSUE THREAD

**Issue by s1l3ntstorm** [bogenpirat/MMM-WetterOnline#4]
Good morning :-)
I think your module looks very nice and would like to install it on my MM. I followed the instructions and as far as I understand it, I have to copy the location URL from Wetteronline so that it looks like this in the end:

{
module: 'MMM-WeatherOnline',
position: "top_right",
config: {

        useHeader: true,
        header: "Hemau weather",
        city: "https://www.wetteronline.de/wetter/hemau/hohenschambach",
        width: "400px",
        daysTrend: 4,
        updateIntervalMins: 5,
        
                    }
                },

Unfortunately, nothing is displayed for me at all. Did I miss something or enter it incorrectly? It would be great if you could help me.

I created a post for this here, although English is not my strength :-)
https://forum.magicmirror.builders/topic/18088/mmm-wetteronline-does-not-load

**Comment by s1l3ntstorm** [comment]
city: "hemau", in now it works - thanks for the module

**Comment by KristjanESPERANTO** [comment]
Nice, that you figured it out! Since the module works for you, please close this issue :slightly_smiling_face:
