### ISSUE TITLE
Module won't start

### ISSUE THREAD

**Issue by Cl0udbuster** [bogenpirat/MMM-WetterOnline#7]
Hello ^^
I followed the instructions and as far as I understand it, everything looks fine but the module is not displayed.
The config looks like that:

{
module: 'MMM-WetterOnline',
position: "top_right",
config: {
    city: "koeln",
    width: "400px",
    daysTrend: 4,
    updateIntervalMins: 5,
    
                }
            },

Did I miss something or enter it incorrectly? It would be great if you could help me.

**Comment by bogenpirat** [comment]
looks about right at first glance. did you install the module correctly (i.e. in the correct folders, followed all the steps etc.)?

**Comment by Cl0udbuster** [comment]
Followed all steps and installed it under 

/home/"User"/MagicMirror/modules

Looks like it's not a problem with the module itself.
I installed some more Modules and every module which using internet connection doesn't pop up or shows only loading.

Any idea where or what I can best look for?

**Comment by bogenpirat** [comment]
MagicMirror writes logs, your best bet would be looking at those. good luck!
